import { Pet } from "@/types/Pet.type";

export const petsMock: Pet[] = [
  {
    id: "G9yfpaxEv",
    url: "https://cdn2.thedogapi.com/images/G9yfpaxEv.jpg",
    width: 297,
    height: 447,
    name: "Dusty",
    age: 13,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "a95",
    url: "https://cdn2.thecatapi.com/images/a95.jpg",
    width: 480,
    height: 360,
    name: "Maggie",
    age: 6,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "3ig",
    url: "https://cdn2.thecatapi.com/images/3ig.jpg",
    width: 500,
    height: 357,
    name: "Oscar",
    age: 8,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "cha",
    url: "https://cdn2.thecatapi.com/images/cha.jpg",
    width: 819,
    height: 1024,
    name: "Jack",
    age: 17,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "fq",
    url: "https://cdn2.thecatapi.com/images/fq.jpg",
    width: 2048,
    height: 1536,
    name: "Sheba",
    age: 16,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "a51",
    url: "https://cdn2.thecatapi.com/images/a51.jpg",
    width: 800,
    height: 531,
    name: "Snickers",
    age: 15,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "2o2",
    url: "https://cdn2.thecatapi.com/images/2o2.jpg",
    width: 500,
    height: 348,
    name: "Samantha",
    age: 11,
    species: "cat",
    isFavorite: false,
  },
];
