import { Pet } from "@/types/Pet.type";

export const petsMock: Pet[] = [
  {
    id: "MTYwNTU4NQ",
    url: "https://cdn2.thecatapi.com/images/MTYwNTU4NQ.jpg",
    width: 720,
    height: 960,
    name: "Jasmine",
    age: 4,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "GR68e1Aob",
    url: "https://cdn2.thedogapi.com/images/GR68e1Aob.jpg",
    width: 1280,
    height: 854,
    name: "Sam",
    age: 13,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "ceh",
    url: "https://cdn2.thecatapi.com/images/ceh.jpg",
    width: 520,
    height: 345,
    name: "Socks",
    age: 6,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "xNHN6Vu1e",
    url: "https://cdn2.thedogapi.com/images/xNHN6Vu1e.jpg",
    width: 959,
    height: 958,
    name: "Felix",
    age: 18,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "ROvy59azW",
    url: "https://cdn2.thedogapi.com/images/ROvy59azW.jpg",
    width: 1080,
    height: 1080,
    name: "Rascal",
    age: 17,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "e4h",
    url: "https://cdn2.thecatapi.com/images/e4h.jpg",
    width: 450,
    height: 600,
    name: "Fluffy",
    age: 7,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "b1r",
    url: "https://cdn2.thecatapi.com/images/b1r.jpg",
    width: 480,
    height: 360,
    name: "Gracie",
    age: 10,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "jtrRacj_g",
    url: "https://cdn2.thedogapi.com/images/jtrRacj_g.jpg",
    width: 1080,
    height: 1080,
    name: "Toby",
    age: 2,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "-ipH6e7hG",
    url: "https://cdn2.thedogapi.com/images/-ipH6e7hG.jpg",
    width: 596,
    height: 569,
    name: "Zoey",
    age: 11,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "MTgwMzkyNg",
    url: "https://cdn2.thecatapi.com/images/MTgwMzkyNg.jpg",
    width: 350,
    height: 350,
    name: "George",
    age: 20,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "AHRYwhz-u",
    url: "https://cdn2.thedogapi.com/images/AHRYwhz-u.jpg",
    width: 768,
    height: 1024,
    name: "Gracie",
    age: 17,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "8pe",
    url: "https://cdn2.thecatapi.com/images/8pe.jpg",
    width: 2048,
    height: 1536,
    name: "Kitty",
    age: 19,
    species: "cat",
    isFavorite: false,
  },
  {
    id: "DR1W9HC9A",
    url: "https://cdn2.thedogapi.com/images/DR1W9HC9A.png",
    width: 752,
    height: 498,
    name: "Rascal",
    age: 16,
    species: "dog",
    isFavorite: false,
  },
  {
    id: "zEQtlI8h1",
    url: "https://cdn2.thedogapi.com/images/zEQtlI8h1.jpg",
    width: 960,
    height: 668,
    name: "Milo",
    age: 2,
    species: "dog",
    isFavorite: false,
  },
];
